// +build !ignore_autogenerated

/*
 * Copyright 2018 SUSE LINUX GmbH, Nuernberg, Germany..
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by main. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConfiguration) DeepCopyInto(out *DexConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConfiguration.
func (in *DexConfiguration) DeepCopy() *DexConfiguration {
	if in == nil {
		return nil
	}
	out := new(DexConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConfigurationList) DeepCopyInto(out *DexConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DexConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConfigurationList.
func (in *DexConfigurationList) DeepCopy() *DexConfigurationList {
	if in == nil {
		return nil
	}
	out := new(DexConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DexConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConfigurationSpec) DeepCopyInto(out *DexConfigurationSpec) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StaticClients != nil {
		in, out := &in.StaticClients, &out.StaticClients
		*out = make([]DexStaticClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Certificate = in.Certificate
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConfigurationSpec.
func (in *DexConfigurationSpec) DeepCopy() *DexConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(DexConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConfigurationStatus) DeepCopyInto(out *DexConfigurationStatus) {
	*out = *in
	out.GeneratedCertificate = in.GeneratedCertificate
	if in.StaticClients != nil {
		in, out := &in.StaticClients, &out.StaticClients
		*out = make([]DexStaticClientStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConfigurationStatus.
func (in *DexConfigurationStatus) DeepCopy() *DexConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(DexConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStaticClient) DeepCopyInto(out *DexStaticClient) {
	*out = *in
	if in.RedirectURLs != nil {
		in, out := &in.RedirectURLs, &out.RedirectURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStaticClient.
func (in *DexStaticClient) DeepCopy() *DexStaticClient {
	if in == nil {
		return nil
	}
	out := new(DexStaticClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexStaticClientStatus) DeepCopyInto(out *DexStaticClientStatus) {
	*out = *in
	if in.RedirectURLs != nil {
		in, out := &in.RedirectURLs, &out.RedirectURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Password = in.Password
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexStaticClientStatus.
func (in *DexStaticClientStatus) DeepCopy() *DexStaticClientStatus {
	if in == nil {
		return nil
	}
	out := new(DexStaticClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConnector) DeepCopyInto(out *LDAPConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConnector.
func (in *LDAPConnector) DeepCopy() *LDAPConnector {
	if in == nil {
		return nil
	}
	out := new(LDAPConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LDAPConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConnectorList) DeepCopyInto(out *LDAPConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LDAPConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConnectorList.
func (in *LDAPConnectorList) DeepCopy() *LDAPConnectorList {
	if in == nil {
		return nil
	}
	out := new(LDAPConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LDAPConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConnectorSpec) DeepCopyInto(out *LDAPConnectorSpec) {
	*out = *in
	out.User = in.User
	out.Group = in.Group
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConnectorSpec.
func (in *LDAPConnectorSpec) DeepCopy() *LDAPConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(LDAPConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConnectorStatus) DeepCopyInto(out *LDAPConnectorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConnectorStatus.
func (in *LDAPConnectorStatus) DeepCopy() *LDAPConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(LDAPConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupSpec) DeepCopyInto(out *LDAPGroupSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupSpec.
func (in *LDAPGroupSpec) DeepCopy() *LDAPGroupSpec {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPUserSpec) DeepCopyInto(out *LDAPUserSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPUserSpec.
func (in *LDAPUserSpec) DeepCopy() *LDAPUserSpec {
	if in == nil {
		return nil
	}
	out := new(LDAPUserSpec)
	in.DeepCopyInto(out)
	return out
}
